name: flutter_pin_code_widget
description: PIN Code wiget for creating and checking local pin code with flexible settings.
version: 0.0.4+1
homepage: https://github.com/AgoraDesk-LocalMonero/flutter-pin-code-widget

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: